addons:
  apt:
    packages:
      - libboost1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-program-options1.55-dev
      - libboost-serialization1.55-dev
      - libboost-system1.55-dev
      - libboost-test1.55-dev
      - libboost-thread1.55-dev
      - libzmq-dev
    sources:
      - boost-latest

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
compiler:
  - clang
  - gcc

env: SIMPATH=/usr

language: cpp

script:
  - make
  - make test

sudo: false
